### ISSUE TITLE
Call for contributers

### ISSUE THREAD

**Issue by robbynshaw** [robbynshaw/we-are-sorry.com#1]
> See [readme](https://github.com/robbynshaw/we-are-sorry.com) for an overview

I would like you to collaborate on this project with me.

To make this happen, we will need a lot of people for a lot of different tasks, coding and otherwise, and we will need to get started immediately. **There will be a planning meeting tonight at 8PM CST.** If you would like to contribute, please add a comment to this issue.

If you have any initial ideas, please comment them below as well so that we can proceed as efficiently as possible in the meeting.

```
Topic: we-are-sorry.com Initial Planning
Time: Jun 2, 2020 08:00 PM Central Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/75666659684?pwd=a3kvMG9EcGswU2hiQmpnMFgvN2t3QT09

Meeting ID: 756 6665 9684
Password: 76916ad53b
```

**Comment by kcbaggins** [comment]
I would like to contribute. Need some time to process your ideas before suggesting any ideas.

**Comment by sbloom82** [comment]
Hi rob. I will listen to your ideas.

**Comment by robbynshaw** [comment]
Thank you everyone for listening and contributing to the discussion! I will post some notes and a signup sheet (and hopefully a demo) as soon as possible!

Thanks again!

**Comment by robbynshaw** [comment]
First run at an example app is up now @ https://we-are-sorry-com.now.sh/

If anyone wants to write up some example components, that would be grand!

**Comment by leahbala** [comment]
Hey Robby, This is awesome. So thankful for you and that you're doing this.
 I want to help, have no idea how to code but am good with other things, advocacy, creativity, etc.
I don't know if this would be a fit, but maybe if people could have space to share art like a picture somewhere in conjunction with collaborating. Space to celebrate race.

**Comment by kcbaggins** [comment]
> 
> 
> First run at an example app is up now @ https://we-are-sorry-com.now.sh/
> 
> If anyone wants to write up some example components, that would be grand!

I appreciate your speed getting this up. Very helpful and I have better understanding than I did in the launch meeting.

**Comment by embuhrow** [comment]
Hey Rob, not sure how much time I can lend to the cause, but I'd be happy to help out where I can.

**Comment by robbynshaw** [comment]
Hey folks, I added a [roadmap](https://github.com/robbynshaw/we-are-sorry.com/blob/master/ROADMAP.md). Please check it out if you want to help out.

**Comment by robbynshaw** [comment]
As we currently don't have enough support for this project, I will be moving on to find other ways to help.

I recommend using [Anguish and Action](https://www.obama.org/anguish-and-action) from the Obama foundation for anyone looking for a similar *hub* for resources at this present time.

Thanks for the support, everyone!
